/* u02B0.h */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/* Copyright (C) 2006-2022 Stuart Swales */

#ifndef __u02B0_h
#define __u02B0_h

/*
02B0..02FF Spacing Modifier Letters
*/

#define UCH_MODIFIER_LETTER_SMALL_H 0x02B0U
#define UCH_MODIFIER_LETTER_SMALL_H_WITH_HOOK 0x02B1U
#define UCH_MODIFIER_LETTER_SMALL_J 0x02B2U
#define UCH_MODIFIER_LETTER_SMALL_R 0x02B3U
#define UCH_MODIFIER_LETTER_SMALL_TURNED_R 0x02B4U
#define UCH_MODIFIER_LETTER_SMALL_TURNED_R_WITH_HOOK 0x02B5U
#define UCH_MODIFIER_LETTER_SMALL_CAPITAL_INVERTED_R 0x02B6U
#define UCH_MODIFIER_LETTER_SMALL_W 0x02B7U
#define UCH_MODIFIER_LETTER_SMALL_Y 0x02B8U
#define UCH_MODIFIER_LETTER_PRIME 0x02B9U
#define UCH_MODIFIER_LETTER_DOUBLE_PRIME 0x02BAU
#define UCH_MODIFIER_LETTER_TURNED_COMMA 0x02BBU
#define UCH_MODIFIER_LETTER_APOSTROPHE 0x02BCU
#define UCH_MODIFIER_LETTER_REVERSED_COMMA 0x02BDU
#define UCH_MODIFIER_LETTER_RIGHT_HALF_RING 0x02BEU
#define UCH_MODIFIER_LETTER_LEFT_HALF_RING 0x02BFU

#define UCH_MODIFIER_LETTER_GLOTTAL_STOP 0x02C0U
#define UCH_MODIFIER_LETTER_REVERSED_GLOTTAL_STOP 0x02C1U
#define UCH_MODIFIER_LETTER_LEFT_ARROWHEAD 0x02C2U
#define UCH_MODIFIER_LETTER_RIGHT_ARROWHEAD 0x02C3U
#define UCH_MODIFIER_LETTER_UP_ARROWHEAD 0x02C4U
#define UCH_MODIFIER_LETTER_DOWN_ARROWHEAD 0x02C5U
#define UCH_MODIFIER_LETTER_CIRCUMFLEX_ACCENT 0x02C6U
#define UCH_CARON 0x02C7U
#define UCH_MODIFIER_LETTER_VERTICAL_LINE 0x02C8U
#define UCH_MODIFIER_LETTER_MACRON 0x02C9U
#define UCH_MODIFIER_LETTER_ACUTE_ACCENT 0x02CAU
#define UCH_MODIFIER_LETTER_GRAVE_ACCENT 0x02CBU
#define UCH_MODIFIER_LETTER_LOW_VERTICAL_LINE 0x02CCU
#define UCH_MODIFIER_LETTER_LOW_MACRON 0x02CDU
#define UCH_MODIFIER_LETTER_LOW_GRAVE_ACCENT 0x02CEU
#define UCH_MODIFIER_LETTER_LOW_ACUTE_ACCENT 0x02CFU

#define UCH_MODIFIER_LETTER_TRIANGULAR_COLON 0x02D0U
#define UCH_MODIFIER_LETTER_HALF_TRIANGULAR_COLON 0x02D1U
#define UCH_MODIFIER_LETTER_CENTRED_RIGHT_HALF_RING 0x02D2U
#define UCH_MODIFIER_LETTER_CENTRED_LEFT_HALF_RING 0x02D3U
#define UCH_MODIFIER_LETTER_UP_TACK 0x02D4U
#define UCH_MODIFIER_LETTER_DOWN_TACK 0x02D5U
#define UCH_MODIFIER_LETTER_PLUS_SIGN 0x02D6U
#define UCH_MODIFIER_LETTER_MINUS_SIGN 0x02D7U
#define UCH_BREVE 0x02D8U
#define UCH_DOT_ABOVE 0x02D9U
#define UCH_RING_ABOVE 0x02DAU
#define UCH_OGONEK 0x02DBU
#define UCH_SMALL_TILDE 0x02DCU
#define UCH_DOUBLE_ACUTE_ACCENT 0x02DDU
#define UCH_MODIFIER_LETTER_RHOTIC_HOOK 0x02DEU
#define UCH_MODIFIER_LETTER_CROSS_ACCENT 0x02DFU

#define UCH_MODIFIER_LETTER_SMALL_GAMMA 0x02E0U
#define UCH_MODIFIER_LETTER_SMALL_L 0x02E1U
#define UCH_MODIFIER_LETTER_SMALL_S 0x02E2U
#define UCH_MODIFIER_LETTER_SMALL_X 0x02E3U
#define UCH_MODIFIER_LETTER_SMALL_REVERSED_GLOTTAL_STOP 0x02E4U
#define UCH_MODIFIER_LETTER_EXTRA_HIGH_TONE_BAR 0x02E5U
#define UCH_MODIFIER_LETTER_HIGH_TONE_BAR 0x02E6U
#define UCH_MODIFIER_LETTER_MID_TONE_BAR 0x02E7U
#define UCH_MODIFIER_LETTER_LOW_TONE_BAR 0x02E8U
#define UCH_MODIFIER_LETTER_EXTRA_LOW_TONE_BAR 0x02E9U
#define UCH_MODIFIER_LETTER_YIN_DEPARTING_TONE_MARK 0x02EAU
#define UCH_MODIFIER_LETTER_YANG_DEPARTING_TONE_MARK 0x02EBU
#define UCH_MODIFIER_LETTER_VOICING 0x02ECU
#define UCH_MODIFIER_LETTER_UNASPIRATED 0x02EDU
#define UCH_MODIFIER_LETTER_DOUBLE_APOSTROPHE 0x02EEU
#define UCH_MODIFIER_LETTER_LOW_DOWN_ARROWHEAD 0x02EFU

#define UCH_MODIFIER_LETTER_LOW_UP_ARROWHEAD 0x02F0U
#define UCH_MODIFIER_LETTER_LOW_LEFT_ARROWHEAD 0x02F1U
#define UCH_MODIFIER_LETTER_LOW_RIGHT_ARROWHEAD 0x02F2U
#define UCH_MODIFIER_LETTER_LOW_RING 0x02F3U
#define UCH_MODIFIER_LETTER_MIDDLE_GRAVE_ACCENT 0x02F4U
#define UCH_MODIFIER_LETTER_MIDDLE_DOUBLE_GRAVE_ACCENT 0x02F5U
#define UCH_MODIFIER_LETTER_MIDDLE_DOUBLE_ACUTE_ACCENT 0x02F6U
#define UCH_MODIFIER_LETTER_LOW_TILDE 0x02F7U
#define UCH_MODIFIER_LETTER_RAISED_COLON 0x02F8U
#define UCH_MODIFIER_LETTER_BEGIN_HIGH_TONE 0x02F9U
#define UCH_MODIFIER_LETTER_END_HIGH_TONE 0x02FAU
#define UCH_MODIFIER_LETTER_BEGIN_LOW_TONE 0x02FBU
#define UCH_MODIFIER_LETTER_END_LOW_TONE 0x02FCU
#define UCH_MODIFIER_LETTER_SHELF 0x02FDU
#define UCH_MODIFIER_LETTER_OPEN_SHELF 0x02FEU
#define UCH_MODIFIER_LETTER_LOW_LEFT_ARROW 0x02FFU

#endif /* __u02B0_h */

/* end of u02B0.h */
