/* uFB00.h */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* Copyright (C) 2006-2021 Stuart Swales */

#ifndef __uFB00_h
#define __uFB00_h

/*
FB00..FB4F Alphabetic Presentation Forms
*/

#define UCH_LATIN_SMALL_LIGATURE_FF 0xFB00U
#define UCH_LATIN_SMALL_LIGATURE_FI 0xFB01U
#define UCH_LATIN_SMALL_LIGATURE_FL 0xFB02U
#define UCH_LATIN_SMALL_LIGATURE_FFI 0xFB03U
#define UCH_LATIN_SMALL_LIGATURE_FFL 0xFB04U
#define UCH_LATIN_SMALL_LIGATURE_LONG_S_T 0xFB05U
#define UCH_LATIN_SMALL_LIGATURE_ST 0xFB06U

#define UCH_ARMENIAN_SMALL_LIGATURE_MEN_NOW 0xFB13U
#define UCH_ARMENIAN_SMALL_LIGATURE_MEN_ECH 0xFB14U
#define UCH_ARMENIAN_SMALL_LIGATURE_MEN_INI 0xFB15U
#define UCH_ARMENIAN_SMALL_LIGATURE_VEW_NOW 0xFB16U
#define UCH_ARMENIAN_SMALL_LIGATURE_MEN_XEH 0xFB17U
#define UCH_HEBREW_LETTER_YOD_WITH_HIRIQ 0xFB1DU
#define UCH_HEBREW_POINT_JUDEO_SPANISH_VARIKA 0xFB1EU
#define UCH_HEBREW_LIGATURE_YIDDISH_YOD_YOD_PATAH 0xFB1FU

#define UCH_HEBREW_LETTER_ALTERNATIVE_AYIN 0xFB20U
#define UCH_HEBREW_LETTER_WIDE_ALEF 0xFB21U
#define UCH_HEBREW_LETTER_WIDE_DALET 0xFB22U
#define UCH_HEBREW_LETTER_WIDE_HE 0xFB23U
#define UCH_HEBREW_LETTER_WIDE_KAF 0xFB24U
#define UCH_HEBREW_LETTER_WIDE_LAMED 0xFB25U
#define UCH_HEBREW_LETTER_WIDE_FINAL_MEM 0xFB26U
#define UCH_HEBREW_LETTER_WIDE_RESH 0xFB27U
#define UCH_HEBREW_LETTER_WIDE_TAV 0xFB28U
#define UCH_HEBREW_LETTER_ALTERNATIVE_PLUS_SIGN 0xFB29U
#define UCH_HEBREW_LETTER_SHIN_WITH_SHIN_DOT 0xFB2AU
#define UCH_HEBREW_LETTER_SHIN_WITH_SIN_DOT 0xFB2BU
#define UCH_HEBREW_LETTER_SHIN_WITH_DAGESH_AND_SHIN_DOT 0xFB2CU
#define UCH_HEBREW_LETTER_SHIN_WITH_DAGESH_AND_SIN_DOT 0xFB2DU
#define UCH_HEBREW_LETTER_ALEF_WITH_PATAH 0xFB2EU
#define UCH_HEBREW_LETTER_ALEF_WITH_QAMATS 0xFB2FU

#define UCH_HEBREW_LETTER_ALEF_WITH_MAPIQ 0xFB30U
#define UCH_HEBREW_LETTER_BET_WITH_DAGESH 0xFB31U
#define UCH_HEBREW_LETTER_GIMEL_WITH_DAGESH 0xFB32U
#define UCH_HEBREW_LETTER_DALET_WITH_DAGESH 0xFB33U
#define UCH_HEBREW_LETTER_HE_WITH_MAPIQ 0xFB34U
#define UCH_HEBREW_LETTER_VAV_WITH_DAGESH 0xFB35U
#define UCH_HEBREW_LETTER_ZAYIN_WITH_DAGESH 0xFB36U
#define UCH_HEBREW_LETTER_TET_WITH_DAGESH 0xFB38U
#define UCH_HEBREW_LETTER_YOD_WITH_DAGESH 0xFB39U
#define UCH_HEBREW_LETTER_FINAL_KAF_WITH_DAGESH 0xFB3AU
#define UCH_HEBREW_LETTER_KAF_WITH_DAGESH 0xFB3BU
#define UCH_HEBREW_LETTER_LAMED_WITH_DAGESH 0xFB3CU
#define UCH_HEBREW_LETTER_MEM_WITH_DAGESH 0xFB3EU

#define UCH_HEBREW_LETTER_NUN_WITH_DAGESH 0xFB40U
#define UCH_HEBREW_LETTER_SAMEKH_WITH_DAGESH 0xFB41U
#define UCH_HEBREW_LETTER_FINAL_PE_WITH_DAGESH 0xFB43U
#define UCH_HEBREW_LETTER_PE_WITH_DAGESH 0xFB44U
#define UCH_HEBREW_LETTER_TSADI_WITH_DAGESH 0xFB46U
#define UCH_HEBREW_LETTER_QOF_WITH_DAGESH 0xFB47U
#define UCH_HEBREW_LETTER_RESH_WITH_DAGESH 0xFB48U
#define UCH_HEBREW_LETTER_SHIN_WITH_DAGESH 0xFB49U
#define UCH_HEBREW_LETTER_TAV_WITH_DAGESH 0xFB4AU
#define UCH_HEBREW_LETTER_VAV_WITH_HOLAM 0xFB4BU
#define UCH_HEBREW_LETTER_BET_WITH_RAFE 0xFB4CU
#define UCH_HEBREW_LETTER_KAF_WITH_RAFE 0xFB4DU
#define UCH_HEBREW_LETTER_PE_WITH_RAFE 0xFB4EU
#define UCH_HEBREW_LIGATURE_ALEF_LAMED 0xFB4FU

#endif /* __uFB00_h */

/* end of uFB00.h */
