/* ob_rec/resource/resource.h */

#define REC_MSG_START (STATUS_MSG_INCREMENT * OBJECT_ID_REC)

#if WINDOWS
#define REC_ID_BM_COM16X15_ID 210
#define REC_ID_BM_COM16X15(n) T5_RESOURCE_COMMON_BMP(REC_ID_BM_COM16X15_ID, n)

#define REC_ID_BM_DB_TOP    REC_ID_BM_COM16X15(0)
#define REC_ID_BM_DB_BOTTOM REC_ID_BM_COM16X15(1)
#define REC_ID_BM_DB_FAST   REC_ID_BM_COM16X15(2)
#define REC_ID_BM_DB_REWIND REC_ID_BM_COM16X15(3)
#define REC_ID_BM_DB_NEXT   REC_ID_BM_COM16X15(4)
#define REC_ID_BM_DB_PREV   REC_ID_BM_COM16X15(5)
#define REC_ID_BM_DB_ADD    REC_ID_BM_COM16X15(6)
#define REC_ID_BM_DB_COPY   REC_ID_BM_COM16X15(8)
#define REC_ID_BM_DB_DEL    REC_ID_BM_COM16X15(7)
#define REC_ID_BM_DB_LAYOUT REC_ID_BM_COM16X15(8)
#define REC_ID_BM_DB_CHART  REC_ID_BM_COM16X15(8)
#define REC_ID_BM_DB_GOTO   REC_ID_BM_COM16X15(8)
#define REC_ID_BM_DB_PROP   REC_ID_BM_COM16X15(8)
#else
#define REC_ID_BM_DB_TOP    "DB_TOP"
#define REC_ID_BM_DB_BOTTOM "DB_BOTTOM"
#define REC_ID_BM_DB_FAST   "DB_FAST"
#define REC_ID_BM_DB_REWIND "DB_REWIND"
#define REC_ID_BM_DB_NEXT   "DB_NEXT"
#define REC_ID_BM_DB_PREV   "DB_PREV"
#define REC_ID_BM_DB_COPY   "DB_COPY"
#define REC_ID_BM_DB_ADD    "DB_ADD"
#define REC_ID_BM_DB_DEL    "DB_DEL"
#define REC_ID_BM_DB_LAYOUT "DB_LAYOUT"
#define REC_ID_BM_DB_CHART  "DB_CHART"
#define REC_ID_BM_DB_GOTO   "DB_GOTO"
#define REC_ID_BM_DB_PROP   "DB_PROP"
#endif

#define REC_MSG_FIRST_TEXT         (REC_MSG_START + 0)
#define REC_MSG_SEARCH_CAPTION     (REC_MSG_START + 1)
#define REC_MSG_QUERY_CAPTION      (REC_MSG_START + 2)
#define REC_MSG_WHOLE_FILE         (REC_MSG_START + 3)
#define REC_MSG_VIEW_QUERY         (REC_MSG_START + 4)
#define REC_MSG_REFINE_QUERY       (REC_MSG_START + 5)
#define REC_MSG_EXTEND_QUERY       (REC_MSG_START + 6)
#define REC_MSG_EXCLUDE_QUERY      (REC_MSG_START + 7)
#define REC_MSG_CHANGE_QUERY       (REC_MSG_START + 8)
#define REC_MSG_DELETE_QUERY       (REC_MSG_START + 9)
#define REC_MSG_NEW_QUERY          (REC_MSG_START +10)

#define REC_MSG_OPERATOR_IS        (REC_MSG_START + 11)
#define REC_MSG_OPERATOR_ISNT      (REC_MSG_START + 12)
#define REC_MSG_OPERATOR_CONTAINS  (REC_MSG_START + 13)
#define REC_MSG_OPERATOR_NOTCONT   (REC_MSG_START + 14)
#define REC_MSG_OPERATOR_GREATER   (REC_MSG_START + 15)
#define REC_MSG_OPERATOR_LESS      (REC_MSG_START + 16)
#define REC_MSG_OPERATOR_DONTCARE  (REC_MSG_START + 17)
#define REC_MSG_OPERATOR_ISEMPTY   (REC_MSG_START + 18)
#define REC_MSG_OPERATOR_NOTEMPTY  (REC_MSG_START + 19)
#define REC_MSG_OPERATOR_EXPRESS   (REC_MSG_START + 20)

#define REC_MSG_OPERATOR_BASE      REC_MSG_OPERATOR_IS
#define REC_MSG_OPERATOR_LAST      REC_MSG_OPERATOR_EXPRESS

#define REC_MSG_CARDS_GROUP     (REC_MSG_START + 21)
#define REC_MSG_FIELDS_GROUP    (REC_MSG_START + 22)
#define REC_MSG_FIELDS_ALL       (REC_MSG_START + 23)
#define REC_MSG_FIELDS_ANY       (REC_MSG_START + 24)
#define REC_MSG_CARDS_KEEP       (REC_MSG_START + 25)
#define REC_MSG_CARDS_DISCARD    (REC_MSG_START + 26)

#define REC_MSG_EDIT_CAPTION (REC_MSG_START + 27)

#define REC_MSG_LAYOUT_CARD    (REC_MSG_START + 28)
#define REC_MSG_LAYOUT_SHEET   (REC_MSG_START + 29)
#define REC_MSG_LAYOUT_SHOW    (REC_MSG_START + 30)
#define REC_MSG_LAYOUT_HIDDEN  (REC_MSG_START + 31)
#define REC_MSG_LAYOUT_CAPTION (REC_MSG_START + 32)
#define REC_MSG_LAYOUT_TITLES  (REC_MSG_START + 33)
#define REC_MSG_TYPE_GROUP     (REC_MSG_START + 34)
#define REC_MSG_TEXT_ACROSS    (REC_MSG_START + 35)
#define REC_MSG_AUTO_ROWS      (REC_MSG_START + 36)
#define REC_MSG_TEXT_DEEP      (REC_MSG_START + 37)

#define REC_MSG_PROP_GROUP   (REC_MSG_START + 39)

#define REC_MSG_SORT_TITLE   (REC_MSG_START + 40)
#define REC_MSG_SORT_UP      (REC_MSG_START + 41)
#define REC_MSG_SORT_DOWN    (REC_MSG_START + 42)
#define REC_MSG_SORT_ORDER   (REC_MSG_START + 43)
#define REC_MSG_CREATE_FILE  (REC_MSG_START + 44)
#define REC_MSG_CREATE_TITLE  (REC_MSG_START + 45)
#define REC_MSG_CREATE_ADD    (REC_MSG_START + 46)
#define REC_MSG_CREATE_REMOVE (REC_MSG_START + 47)

#define REC_MSG_PROP_FIELDTYPE    (REC_MSG_START + 48)
#define REC_MSG_PROP_DEFAULTVALUE (REC_MSG_START + 49)
#define REC_MSG_CHECK_FORMULA     (REC_MSG_START + 50)

#define REC_MSG_PROP_VALUELIST    (REC_MSG_START + 51)
#define REC_MSG_PROP_COMPULSORY   (REC_MSG_START + 52)
#define REC_MSG_PROP_HIDDEN   (REC_MSG_START + 53)
#define REC_MSG_EXPORT_TITLE  (REC_MSG_START + 54)
#define REC_MSG_EXPORT_FORMAT (REC_MSG_START + 55)
#define REC_MSG_EXPORT_CSV    (REC_MSG_START + 56)
#define REC_MSG_EXPORT_DP     (REC_MSG_START + 57)
#define REC_MSG_EXPORT_LEAFNAME (REC_MSG_START + 58)

#define REC_MSG_FIELD_TYPE_TEXT    (REC_MSG_START + 60)
#define REC_MSG_FIELD_TYPE_NUMBER  (REC_MSG_START + 61)
#define REC_MSG_FIELD_TYPE_DATE    (REC_MSG_START + 62)
#define REC_MSG_FIELD_TYPE_INTEGER    (REC_MSG_START + 63)
#define REC_MSG_FIELD_TYPE_BOOLEAN (REC_MSG_START + 64)
#define REC_MSG_FIELD_TYPE_PICTURE (REC_MSG_START + 65)
#define REC_MSG_FIELD_TYPE_FILE    (REC_MSG_START + 66)
#define REC_MSG_FIELD_TYPE_FORMULA (REC_MSG_START + 67)
#define REC_MSG_FIELD_TYPE_INTERVAL (REC_MSG_START + 68)
#define REC_MSG_FIELD_TYPE_BASE   (REC_MSG_FIELD_TYPE_TEXT)
#define REC_MSG_FIELD_TYPE_LAST   (REC_MSG_FIELD_TYPE_INTERVAL)

#define REC_MSG_STATUS_SEARCH_EXTEND (REC_MSG_START + 70)
#define REC_MSG_STATUS_LINE_WHOLE  (REC_MSG_START + 71)
/* and 72 reserved */

#define REC_MSG_PSWD_TITLE   (REC_MSG_START + 73)
#define REC_MSG_PSWD_BLANKOK (REC_MSG_START + 74)

#define REC_MSG_TEXT_AND           (REC_MSG_START + 75)
#define REC_MSG_TEXT_OR            (REC_MSG_START + 76)
#define REC_MSG_TEXT_EXCLUDING     (REC_MSG_START + 77)

#define REC_MSG_STATUS_LINE_EMPTY_TEMPLATE (REC_MSG_START + 78)
#define REC_MSG_STATUS_LINE_EMPTY_DOCUMENT (REC_MSG_START + 79)

#define REC_MSG_STATUS_DB_TOP      (REC_MSG_START + 80)
#define REC_MSG_STATUS_DB_BOTTOM   (REC_MSG_START + 81)
#define REC_MSG_STATUS_DB_FAST     (REC_MSG_START + 82)
#define REC_MSG_STATUS_DB_REWIND   (REC_MSG_START + 83)
#define REC_MSG_STATUS_DB_NEXT     (REC_MSG_START + 84)
#define REC_MSG_STATUS_DB_PREV     (REC_MSG_START + 85)
#define REC_MSG_STATUS_DB_ADD      (REC_MSG_START + 86)
#define REC_MSG_STATUS_DB_DEL      (REC_MSG_START + 87)
#define REC_MSG_STATUS_DB_LAYOUT   (REC_MSG_START + 88)
#define REC_MSG_STATUS_DB_PROP     (REC_MSG_START + 89)
#define REC_MSG_STATUS_DB_COPY     (REC_MSG_START + 69)

#define REC_MSG_STYLE_INTRO_CAPTION    (REC_MSG_START + 90)
#define REC_MSG_STYLE_INTRO_DATABASE   (REC_MSG_START + 91)
#define REC_MSG_STYLE_INTRO_ALL_FIELDS    (REC_MSG_START + 92)
#define REC_MSG_STYLE_INTRO_ALL_TITLES    (REC_MSG_START + 93)
#define REC_MSG_STYLE_INTRO_ANON_FIELD    (REC_MSG_START + 94)
#define REC_MSG_STYLE_EDITING_CAPTION    (REC_MSG_START + 95)

#define REC_MSG_STATUS_LINE_SUBSET (REC_MSG_START + 96)
/* and 97 reserved */
#define REC_MSG_STATUS_AUTO_WIDTHING (REC_MSG_START + 98)
#define REC_MSG_STATUS_STYLE_EXTEND  (REC_MSG_START + 99)
#define REC_MSG_STATUS_LINE_FIELD (REC_MSG_START + 100)
#define REC_MSG_STATUS_LINE_TITLE (REC_MSG_START + 101)

#define REC_MSG_VL_IN (REC_MSG_START + 102)
#define REC_MSG_VL_NN (REC_MSG_START + 103)

#define REC_MSG_VL_BASE REC_MSG_VL_IN
#define REC_MSG_VL_LAST REC_MSG_VL_NN

#define REC_MSG_VALUE_CAPTION (REC_MSG_START + 104)

#define REC_MSG_VIEW_EXPLAIN_REFINE (REC_MSG_START + 110)
#define REC_MSG_VIEW_EXPLAIN_EXTEND (REC_MSG_START + 111)
#define REC_MSG_VIEW_EXPLAIN_CHANGE (REC_MSG_START + 112)
#define REC_MSG_SORT_RENAME         (REC_MSG_START + 113)
#define REC_MSG_STATUS_DB_CHART     (REC_MSG_START + 114)
#define REC_MSG_STATUS_DB_GOTO      (REC_MSG_START + 115)
#define REC_MSG_GOTO_CAPTION        (REC_MSG_START + 116)
#define REC_MSG_GOTO_RECORD_NUMBER  (REC_MSG_START + 117)
#define REC_MSG_DELETE_QUESTION     (REC_MSG_START + 118)

#define REC_ERR_START (STATUS_ERR_INCREMENT * OBJECT_ID_REC)
#define REC_ERR_DATABASE_NOT_OPEN (REC_ERR_START-0)
#define REC_ERR_ERROR_RQ (REC_ERR_START-1)
#define REC_ERR_MERGE_ON_SERVER (REC_ERR_START-2)
#define REC_ERR_RECORD_LOCKED (REC_ERR_START-3)
#define REC_ERR_SORT_ON_SERVER (REC_ERR_START-4)
#define REC_ERR_PROP_ON_SERVER (REC_ERR_START-5)
#define REC_ERR_DOC_NOT_SAVED (REC_ERR_START-6)
#define REC_ERR_CANT_OPEN_DB (REC_ERR_START-8)
#define REC_ERR_CANT_LOAD_SCRAP (REC_ERR_START-9)
#define REC_ERR_NO_DATABASE (REC_ERR_START-10)
#define REC_ERR_CHECK_FAILED (REC_ERR_START-11)
#define REC_ERR_CANT_IMPORT (REC_ERR_START-12)
#define REC_ERR_CANT_CREATE_DB_ISAFILE (REC_ERR_START-13)
#define REC_ERR_NO_ACCESS_FOR_ITEM (REC_ERR_START-14)
#define REC_ERR_ALREADY_A_FIELD (REC_ERR_START-15)
#define REC_ERR_FIELD_NAME_BLANK (REC_ERR_START-16)
#define REC_ERR_ALREADY_OPEN_IN (REC_ERR_START-17)
#define REC_ERR_NO_ACCESS_ADD (REC_ERR_START-18)
#define REC_ERR_NO_ACCESS_DELETE (REC_ERR_START-19)
#define REC_ERR_NO_ACCESS_LAYOUT (REC_ERR_START-20)
#define REC_ERR_NO_ACCESS_READ (REC_ERR_START-21)
#define REC_ERR_NO_ACCESS_SAVE (REC_ERR_START-22)
#define REC_ERR_NO_ACCESS_SEARCH (REC_ERR_START-23)
#define REC_ERR_NO_ACCESS_SORT (REC_ERR_START-24)
#define REC_ERR_NO_ACCESS_TO_DATABASE (REC_ERR_START-25)
#define REC_ERR_NO_VISIBLE_FIELDS (REC_ERR_START-26)

/*
internal errors - may not matter if no msg 'cos they shouldn't get to user ho ho
*/

#define REC_ERR_DB_NOT_OK (REC_ERR_START-100)
#define REC_ERR_BAD_TABLEDEF (REC_ERR_START-101)
#define REC_ERR_BAD_DB_LOAD (REC_ERR_START-102)
#define REC_ERR_BAD_FIELD (REC_ERR_START-103)
#define REC_ERR_NO_QUERY (REC_ERR_START-104)
#define REC_ERR_BAD_FIELD_ID (REC_ERR_START-105)
#define REC_ERR_NO_ACCESS_EDIT (REC_ERR_START-106)
#define REC_ERR_DUPLICATE_QUERY_ID (REC_ERR_START-107)
#define REC_ERR_FIELD_NOT_READABLE (REC_ERR_START-108)

/* end of ob_rec/resource/resource.h */
