/* ob_ruler.h */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* Copyright (C) 1993-1998 Colton Software Limited
 * Copyright (C) 1998-2015 R W Colton */

/* Ruler object module for Fireworkz */

/* SKS June 1993 separated out from skel */

/*
messages
*/

#define RULER_MSG_BASE  (STATUS_MSG_INCREMENT * OBJECT_ID_RULER)

#define RULER_MSG(n)    (RULER_MSG_BASE + (n))

#define RULER_MSG_STATUS_RULER_HORZ_NO_MARK       RULER_MSG(1)
#define RULER_MSG_STATUS_RULER_VERT_NO_MARK       RULER_MSG(2)
#define RULER_MSG_STATUS_RULER_HORZ_NO_MARK_VALID RULER_MSG(3)

#define RULER_MSG_STATUS_RULER_HORZ_PLACE_TAB     RULER_MSG(274)
#define RULER_MSG_STATUS_RULER_HORZ_TAB_LEFT      RULER_MSG(275)
#define RULER_MSG_STATUS_RULER_HORZ_TAB_CENTRE    RULER_MSG(276)
#define RULER_MSG_STATUS_RULER_HORZ_TAB_RIGHT     RULER_MSG(277)
#define RULER_MSG_STATUS_RULER_HORZ_TAB_DECIMAL   RULER_MSG(278)
#define RULER_MSG_STATUS_RULER_HORZ_DRAG_TAB      RULER_MSG(279)
#define RULER_MSG_STATUS_RULER_HORZ_MARGIN_LEFT   RULER_MSG(285)
#define RULER_MSG_STATUS_RULER_HORZ_MARGIN_PARA   RULER_MSG(286)
#define RULER_MSG_STATUS_RULER_HORZ_MARGIN_RIGHT  RULER_MSG(287)
#define RULER_MSG_STATUS_RULER_HORZ_DRAG_MARGIN   RULER_MSG(288)
#define RULER_MSG_STATUS_RULER_HORZ_COL_WIDTH     RULER_MSG(729)

#define RULER_MSG_STATUS_RULER_VERT_HEADER_MARGIN RULER_MSG(723)
#define RULER_MSG_STATUS_RULER_VERT_FOOTER_MARGIN RULER_MSG(724)
#define RULER_MSG_STATUS_RULER_VERT_ROW_HEIGHT    RULER_MSG(725)
#define RULER_MSG_STATUS_RULER_VERT_HEADER_OFFSET RULER_MSG(727)
#define RULER_MSG_STATUS_RULER_VERT_FOOTER_OFFSET RULER_MSG(728)

/* end of ob_ruler.h */
