/* ui_hefo.c */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* Copyright (C) 1993-1998 Colton Software Limited
 * Copyright (C) 1998-2015 R W Colton */

/* Header/footer editing UI for Fireworkz */

/* SKS October 1994 */

#include "common/gflags.h"

#include "ob_hefo/ui_hefin.h"

#include "ob_story/ob_story.h"

#include "ob_hefo/ob_hefo.h"

#ifndef         __xp_skeld_h
#include "ob_skel/xp_skeld.h"
#endif

#define HEADER_DEFAULT_MARGIN (FP_PIXITS_PER_CM * 1)
#define HEADER_DEFAULT_OFFSET (68) /* same as in Letter template */

#define FOOTER_DEFAULT_MARGIN  (FP_PIXITS_PER_CM * 1)
#define FOOTER_DEFAULT_OFFSET ((FP_PIXITS_PER_CM * 4) / 10)

static FP_PIXIT
page_hefo_break_values_fp_pixits_per_user_unit;

static F64
page_hefo_break_values_user_unit_multiple;

static UCHARZ
page_hefo_break_values_user_unit_numform_ustr_buf[elemof32("0.,###")];

static STATUS
page_hefo_break_values_user_unit_resource_id;

/******************************************************************************
*
* edit header/footer info controls
*
******************************************************************************/

enum PAGE_HEFO_BREAK_VALUES_IDS
{
    PAGE_HEFO_BREAK_VALUES_ID_PAGE_BREAK = 110,
    PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER,

#define PAGE_HEFO_BREAK_VALUES_FIELDS_H DIALOG_BUMP_H(5)
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP = 200,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_CAPTION_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN_UNITS,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET_UNITS,

    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP = 220,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_CAPTION_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN_UNITS,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET_UNITS,

    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP = 240,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_CAPTION_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN_UNITS,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET_UNITS,

    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP = 300,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_CAPTION_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN_UNITS,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET_UNITS,

    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP = 320,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_CAPTION_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN_UNITS,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET_UNITS,

    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP = 340,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_CAPTION_GROUP2,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN_UNITS,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET_LABEL,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET_UNITS,

    PAGE_HEFO_BREAK_VALUES_ID_MAX
};

static /*poked*/ DIALOG_CONTROL_DATA_STATICTEXT
page_hefo_break_values_hf_oef_units_data = { { UI_TEXT_TYPE_NONE }, { 1 /*left_text*/, 0 /*centre_text*/, 1 /*windows_no_colon*/ } };

static const DIALOG_CONTROL_DATA_STATICTEXT
page_hefo_break_values_hf_oef_margin_label_data = { UI_TEXT_INIT_RESID(MSG_DIALOG_PAGE_HEFO_BREAK_VALUES_MARGIN) };

static const DIALOG_CONTROL_DATA_STATICTEXT
page_hefo_break_values_hf_oef_offset_label_data = { UI_TEXT_INIT_RESID(MSG_DIALOG_PAGE_HEFO_BREAK_VALUES_OFFSET) };

static /*poked*/ UI_CONTROL_F64
page_hefo_break_values_units_control;

/*
header odd group
*/

static const DIALOG_CONTROL
page_hefo_break_values_header_odd_group =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP, DIALOG_MAIN_GROUP,
    { DIALOG_CONTROL_PARENT, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { 0, 0, DIALOG_STDGROUP_RM, DIALOG_STDGROUP_BM },
    { DRT(LTRB, GROUPBOX) }
};

static const DIALOG_CONTROL_DATA_GROUPBOX
page_hefo_break_values_header_odd_group_data = { UI_TEXT_INIT_RESID(MSG_DIALOG_PAGE_HEFO_BREAK_VALUES_HEADER_ODD), { FRAMED_BOX_GROUP } };

static const DIALOG_CONTROL
page_hefo_break_values_header_odd_enable =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_ENABLE, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP2, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP2 },
    { DIALOG_STDGROUP_LM, 0, DIALOG_STDCHECK_H, 0 },
    { DRT(LTLB, CHECKBOX), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_CHECKBOXF
page_hefo_break_values_header_odd_enable_data = { { { 0, 1 /*move_focus*/ }, { UI_TEXT_TYPE_NONE } }, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN };

static const DIALOG_CONTROL
page_hefo_break_values_header_odd_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_ENABLE, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { DIALOG_STDSPACING_H, DIALOG_STDGROUP_TM, 0, 0 },
    { DRT(RTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

static const DIALOG_CONTROL
page_hefo_break_values_header_odd_caption_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_CAPTION_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP2,
    { DIALOG_CONTROL_PARENT, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { 0 },
    { DRT(LTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

/*
margin
*/

static const DIALOG_CONTROL
page_hefo_break_values_header_odd_margin_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_CAPTION_GROUP2,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_header_odd_margin =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_CAPTION_GROUP2, DIALOG_CONTROL_PARENT },
    { DIALOG_STDSPACING_H, 0, PAGE_HEFO_BREAK_VALUES_FIELDS_H, DIALOG_STDBUMP_V },
    { DRT(RTLT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_header_odd_margin_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_header_odd_margin_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN },
    { DIALOG_LABELGAP_H, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(RTLB, STATICTEXT) }
};

/*
offset
*/

static const DIALOG_CONTROL
page_hefo_break_values_header_odd_offset_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET_LABEL, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_CAPTION_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_header_odd_offset =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN },
    { 0, DIALOG_STDSPACING_V, 0, DIALOG_STDBUMP_V },
    { DRT(LBRT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_header_odd_offset_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_header_odd_offset_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET,
      PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET },
    { 0 },
    { DRT(LTRB, STATICTEXT) }
};

/*
header even group
*/

static const DIALOG_CONTROL
page_hefo_break_values_header_even_group =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP, DIALOG_MAIN_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { 0, DIALOG_STDSPACING_V, DIALOG_STDGROUP_RM, DIALOG_STDGROUP_BM },
    { DRT(LBRB, GROUPBOX) }
};

static const DIALOG_CONTROL_DATA_GROUPBOX
page_hefo_break_values_header_even_group_data = { UI_TEXT_INIT_RESID(MSG_DIALOG_PAGE_HEFO_BREAK_VALUES_HEADER_EVEN), { FRAMED_BOX_GROUP } };

static const DIALOG_CONTROL
page_hefo_break_values_header_even_enable =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_ENABLE, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP2, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP2 },
    { DIALOG_STDGROUP_LM, 0, DIALOG_STDCHECK_H, 0 },
    { DRT(LTLB, CHECKBOX), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_CHECKBOXF
page_hefo_break_values_header_even_enable_data = { { { 0, 1 /*move_focus*/ }, { UI_TEXT_TYPE_NONE } }, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN };

static const DIALOG_CONTROL
page_hefo_break_values_header_even_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_ENABLE, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { DIALOG_STDSPACING_H, DIALOG_STDGROUP_TM, 0, 0 },
    { DRT(RTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

static const DIALOG_CONTROL
page_hefo_break_values_header_even_caption_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_CAPTION_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP2,
    { DIALOG_CONTROL_PARENT, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { 0 },
    { DRT(LTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

/*
margin
*/

static const DIALOG_CONTROL
page_hefo_break_values_header_even_margin_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_CAPTION_GROUP2,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_header_even_margin =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_CAPTION_GROUP2, DIALOG_CONTROL_PARENT },
    { DIALOG_STDSPACING_H, 0, PAGE_HEFO_BREAK_VALUES_FIELDS_H, DIALOG_STDBUMP_V },
    { DRT(RTLT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_header_even_margin_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_header_even_margin_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN },
    { DIALOG_LABELGAP_H, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(RTLB, STATICTEXT) }
};

/*
offset
*/

static const DIALOG_CONTROL
page_hefo_break_values_header_even_offset_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET_LABEL, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_CAPTION_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_header_even_offset =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN },
    { 0, DIALOG_STDSPACING_V, 0, DIALOG_STDBUMP_V },
    { DRT(LBRT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_header_even_offset_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_header_even_offset_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET,
      PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET },
    { 0 },
    { DRT(LTRB, STATICTEXT) }
};

/*
header first group
*/

static const DIALOG_CONTROL
page_hefo_break_values_header_first_group =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP, DIALOG_MAIN_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP, PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_GROUP, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { 0, DIALOG_STDSPACING_V, DIALOG_STDGROUP_RM, DIALOG_STDGROUP_BM },
    { DRT(LBRB, GROUPBOX) }
};

static const DIALOG_CONTROL_DATA_GROUPBOX
page_hefo_break_values_header_first_group_data = { UI_TEXT_INIT_RESID(MSG_DIALOG_PAGE_HEFO_BREAK_VALUES_HEADER_FIRST), { FRAMED_BOX_GROUP } };

static const DIALOG_CONTROL
page_hefo_break_values_header_first_enable =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_ENABLE, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP2, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP2 },
    { DIALOG_STDGROUP_LM, 0, DIALOG_STDCHECK_H, 0 },
    { DRT(LTLB, CHECKBOX), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_CHECKBOXF
page_hefo_break_values_header_first_enable_data = { { { 0, 1 /*move_focus*/ }, { UI_TEXT_TYPE_NONE } }, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN };

static const DIALOG_CONTROL
page_hefo_break_values_header_first_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_ENABLE, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { DIALOG_STDSPACING_H, DIALOG_STDGROUP_TM, 0, 0 },
    { DRT(RTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

static const DIALOG_CONTROL
page_hefo_break_values_header_first_caption_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_CAPTION_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP2,
    { DIALOG_CONTROL_PARENT, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { 0 },
    { DRT(LTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

/*
margin
*/

static const DIALOG_CONTROL
page_hefo_break_values_header_first_margin_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_CAPTION_GROUP2,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_header_first_margin =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_CAPTION_GROUP2, DIALOG_CONTROL_PARENT },
    { DIALOG_STDSPACING_H, 0, PAGE_HEFO_BREAK_VALUES_FIELDS_H, DIALOG_STDBUMP_V },
    { DRT(RTLT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_header_first_margin_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_header_first_margin_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN },
    { DIALOG_LABELGAP_H, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(RTLB, STATICTEXT) }
};

/*
offset
*/

static const DIALOG_CONTROL
page_hefo_break_values_header_first_offset_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET_LABEL, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_CAPTION_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_header_first_offset =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN },
    { 0, DIALOG_STDSPACING_V, 0, DIALOG_STDBUMP_V },
    { DRT(LBRT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_header_first_offset_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_header_first_offset_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET,
      PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET },
    { 0 },
    { DRT(LTRB, STATICTEXT) }
};

/*
footer odd group
*/

static const DIALOG_CONTROL
page_hefo_break_values_footer_odd_group =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP, DIALOG_MAIN_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP, PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { DIALOG_GROUPSPACING_H, 0, DIALOG_STDGROUP_RM, DIALOG_STDGROUP_BM },
    { DRT(RTRB, GROUPBOX) }
};

static const DIALOG_CONTROL_DATA_GROUPBOX
page_hefo_break_values_footer_odd_group_data = { UI_TEXT_INIT_RESID(MSG_DIALOG_PAGE_HEFO_BREAK_VALUES_FOOTER_ODD), { FRAMED_BOX_GROUP } };

static const DIALOG_CONTROL
page_hefo_break_values_footer_odd_enable =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_ENABLE, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP2, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP2 },
    { DIALOG_STDGROUP_LM, 0, DIALOG_STDCHECK_H, 0 },
    { DRT(LTLB, CHECKBOX)}
};

static /*poked*/ DIALOG_CONTROL_DATA_CHECKBOXF
page_hefo_break_values_footer_odd_enable_data = { { { 0, 1 /*move_focus*/ }, { UI_TEXT_TYPE_NONE } }, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN };

static const DIALOG_CONTROL
page_hefo_break_values_footer_odd_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_ENABLE, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { DIALOG_STDSPACING_H, DIALOG_STDGROUP_TM, 0, 0 },
    { DRT(RTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

static const DIALOG_CONTROL
page_hefo_break_values_footer_odd_caption_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_CAPTION_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP2,
    { DIALOG_CONTROL_PARENT, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { 0 },
    { DRT(LTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

/*
margin
*/

static const DIALOG_CONTROL
page_hefo_break_values_footer_odd_margin_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_CAPTION_GROUP2,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_footer_odd_margin =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_CAPTION_GROUP2, DIALOG_CONTROL_PARENT },
    { DIALOG_STDSPACING_H, 0, PAGE_HEFO_BREAK_VALUES_FIELDS_H, DIALOG_STDBUMP_V },
    { DRT(RTLT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_footer_odd_margin_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_footer_odd_margin_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN },
    { DIALOG_LABELGAP_H, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(RTLB, STATICTEXT) }
};

/*
offset
*/

static const DIALOG_CONTROL
page_hefo_break_values_footer_odd_offset_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET_LABEL, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_CAPTION_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_footer_odd_offset =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN },
    { 0, DIALOG_STDSPACING_V, 0, DIALOG_STDBUMP_V },
    { DRT(LBRT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_footer_odd_offset_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_footer_odd_offset_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET,
      PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET },
    { 0 },
    { DRT(LTRB, STATICTEXT) }
};

/*
footer even group
*/

static const DIALOG_CONTROL
page_hefo_break_values_footer_even_group =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP, DIALOG_MAIN_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_GROUP, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { 0, DIALOG_STDSPACING_V, DIALOG_STDGROUP_RM, DIALOG_STDGROUP_BM },
    { DRT(LBRB, GROUPBOX) }
};

static const DIALOG_CONTROL_DATA_GROUPBOX
page_hefo_break_values_footer_even_group_data = { UI_TEXT_INIT_RESID(MSG_DIALOG_PAGE_HEFO_BREAK_VALUES_FOOTER_EVEN), { FRAMED_BOX_GROUP } };

static const DIALOG_CONTROL
page_hefo_break_values_footer_even_enable =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_ENABLE, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP2, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP2 },
    { DIALOG_STDGROUP_LM, 0, DIALOG_STDCHECK_H, 0 },
    { DRT(LTLB, CHECKBOX), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_CHECKBOXF
page_hefo_break_values_footer_even_enable_data = { { { 0, 1 /*move_focus*/ }, { UI_TEXT_TYPE_NONE } }, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN };

static const DIALOG_CONTROL
page_hefo_break_values_footer_even_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_ENABLE, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { DIALOG_STDSPACING_H, DIALOG_STDGROUP_TM, 0, 0 },
    { DRT(RTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

static const DIALOG_CONTROL
page_hefo_break_values_footer_even_caption_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_CAPTION_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP2,
    { DIALOG_CONTROL_PARENT, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { 0 },
    { DRT(LTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

/*
margin
*/

static const DIALOG_CONTROL
page_hefo_break_values_footer_even_margin_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_CAPTION_GROUP2,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_footer_even_margin =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN_LABEL, DIALOG_CONTROL_PARENT },
    { DIALOG_STDSPACING_H, 0, PAGE_HEFO_BREAK_VALUES_FIELDS_H, DIALOG_STDBUMP_V },
    { DRT(RTLT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_footer_even_margin_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_footer_even_margin_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN },
    { DIALOG_LABELGAP_H, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(RTLB, STATICTEXT) }
};

/*
offset
*/

static const DIALOG_CONTROL
page_hefo_break_values_footer_even_offset_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET_LABEL, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_CAPTION_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_footer_even_offset =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN },
    { 0, DIALOG_STDSPACING_V, 0, DIALOG_STDBUMP_V },
    { DRT(LBRT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_footer_even_offset_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_footer_even_offset_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET,
      PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET },
    { 0 },
    { DRT(LTRB, STATICTEXT) }
};

/*
footer first group
*/

static const DIALOG_CONTROL
page_hefo_break_values_footer_first_group =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP, DIALOG_MAIN_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_GROUP, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { 0, DIALOG_STDSPACING_V, DIALOG_STDGROUP_RM, DIALOG_STDGROUP_BM },
    { DRT(LBRB, GROUPBOX) }
};

static const DIALOG_CONTROL_DATA_GROUPBOX
page_hefo_break_values_footer_first_group_data = { UI_TEXT_INIT_RESID(MSG_DIALOG_PAGE_HEFO_BREAK_VALUES_FOOTER_FIRST), { FRAMED_BOX_GROUP } };

static const DIALOG_CONTROL
page_hefo_break_values_footer_first_enable =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_ENABLE, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP2, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP2 },
    { DIALOG_STDGROUP_LM, 0, DIALOG_STDCHECK_H, 0 },
    { DRT(LTLB, CHECKBOX), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_CHECKBOXF
page_hefo_break_values_footer_first_enable_data = { { { 0, 1 /*move_focus*/ }, { UI_TEXT_TYPE_NONE } }, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN };

static const DIALOG_CONTROL
page_hefo_break_values_footer_first_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_ENABLE, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { DIALOG_STDSPACING_H, DIALOG_STDGROUP_TM, 0, 0 },
    { DRT(RTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

static const DIALOG_CONTROL
page_hefo_break_values_footer_first_caption_group2 =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_CAPTION_GROUP2, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP2,
    { DIALOG_CONTROL_PARENT, DIALOG_CONTROL_PARENT, DIALOG_CONTROL_CONTENTS, DIALOG_CONTROL_CONTENTS },
    { 0 },
    { DRT(LTRB, GROUPBOX), 0, 1 /*logical_group*/ }
};

/*
margin
*/

static const DIALOG_CONTROL
page_hefo_break_values_footer_first_margin_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_CAPTION_GROUP2,
    { DIALOG_CONTROL_PARENT, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_footer_first_margin =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_CAPTION_GROUP2, DIALOG_CONTROL_PARENT },
    { DIALOG_STDSPACING_H, 0, PAGE_HEFO_BREAK_VALUES_FIELDS_H, DIALOG_STDBUMP_V },
    { DRT(RTLT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_footer_first_margin_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_footer_first_margin_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN },
    { DIALOG_LABELGAP_H, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(RTLB, STATICTEXT) }
};

/*
offset
*/

static const DIALOG_CONTROL
page_hefo_break_values_footer_first_offset_label =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET_LABEL, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_CAPTION_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN_LABEL, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, STATICTEXT) }
};

static const DIALOG_CONTROL
page_hefo_break_values_footer_first_offset =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN },
    { 0, DIALOG_STDSPACING_V, 0, DIALOG_STDBUMP_V },
    { DRT(LBRT, BUMP_F64), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_F64
page_hefo_break_values_footer_first_offset_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_units_control } /*BUMP_XX*/ };

static const DIALOG_CONTROL
page_hefo_break_values_footer_first_offset_units =
{
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP2,
    { PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET,
      PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN_UNITS, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET },
    { 0 },
    { DRT(LTRB, STATICTEXT) }
};

/*
page break
*/

static const DIALOG_CONTROL
page_hefo_break_values_page_break =
{
    PAGE_HEFO_BREAK_VALUES_ID_PAGE_BREAK, DIALOG_MAIN_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP, PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_GROUP },
    { 0, DIALOG_STDSPACING_V, DIALOG_CONTENTS_CALC, DIALOG_STDCHECK_V },
    { DRT(LBLT, CHECKBOX), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_CHECKBOX
page_hefo_break_values_page_break_data = { { 0 }, UI_TEXT_INIT_RESID(MSG_DIALOG_PAGE_HEFO_BREAK_VALUES_PAGE_BREAK) };

static const DIALOG_CONTROL
page_hefo_break_values_page_number_enable =
{
    PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER_ENABLE, DIALOG_MAIN_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_PAGE_BREAK, PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER },
    { 0, 0, DIALOG_CONTENTS_CALC, 0 },
    { DRT(LTLB, CHECKBOX), 1 /*tabstop*/ }
};

static /*poked*/ DIALOG_CONTROL_DATA_CHECKBOXF
page_hefo_break_values_page_number_enable_data = { { { 0, 1 /*move_focus*/ }, UI_TEXT_INIT_RESID(MSG_DIALOG_PAGE_HEFO_BREAK_VALUES_PAGE_NUMBER) }, PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER };

static const DIALOG_CONTROL
page_hefo_break_values_page_number =
{
    PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER, DIALOG_MAIN_GROUP,
    { PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER_ENABLE, PAGE_HEFO_BREAK_VALUES_ID_PAGE_BREAK },
    { DIALOG_STDSPACING_H, DIALOG_STDSPACING_V, PAGE_HEFO_BREAK_VALUES_FIELDS_H, DIALOG_STDBUMP_V },
    { DRT(RBLT, BUMP_S32), 1 /*tabstop*/ }
};

static const UI_CONTROL_S32
page_hefo_break_values_page_number_control = { 0, S32_MAX };

static /*poked*/ DIALOG_CONTROL_DATA_BUMP_S32
page_hefo_break_values_page_number_data = { { { { FRAMED_BOX_EDIT, 0, 1 /*right_text*/ } } /*EDIT_XX*/, &page_hefo_break_values_page_number_control } /*BUMP_XX*/ };

/*
ok
*/

#if RISCOS

static const DIALOG_CONTROL
page_hefo_break_values_ok =
{
    IDOK, DIALOG_CONTROL_WINDOW,
    { DIALOG_CONTROL_SELF, DIALOG_CONTROL_SELF, PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_GROUP, PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER },
    { DIALOG_CONTENTS_CALC, DIALOG_DEFPUSHBUTTON_V, 0, 0 },
    { DRT(RBRB, PUSHBUTTON), 1 /*tabstop*/ }
};

#else
#define page_hefo_break_values_ok defbutton_ok
#endif

static const DIALOG_CONTROL_ID
argmap_cmd_page_hefo_break_values[] =
{
    0,

    PAGE_HEFO_BREAK_VALUES_ID_PAGE_BREAK,
    PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER,

    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET,

    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET,

    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET,

    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET,

    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET,

    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_ENABLE,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN,
    PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET,
};

static const DIALOG_CONTROL_DATA_PUSH_COMMAND
page_hefo_break_values_ok_command = { T5_CMD_PAGE_HEFO_BREAK_VALUES, OBJECT_ID_HEFO, NULL, argmap_cmd_page_hefo_break_values, { 0, 0, 0, 1 /*lookup_arglist*/ } };

static const DIALOG_CONTROL_DATA_PUSHBUTTON
page_hefo_break_values_ok_data = { { 0 }, UI_TEXT_INIT_RESID(MSG_OK), &page_hefo_break_values_ok_command };

static const DIALOG_CTL_CREATE
page_hefo_break_values_ctl_create[] =
{
    { &dialog_main_group },

    { &page_hefo_break_values_header_odd_group,            &page_hefo_break_values_header_odd_group_data },
    { &page_hefo_break_values_header_odd_group2,           NULL /*&page_hefo_break_values_hf_oef_group2_data*/ },
    { &page_hefo_break_values_header_odd_caption_group2 },
    { &page_hefo_break_values_header_odd_enable,           &page_hefo_break_values_header_odd_enable_data },
    { &page_hefo_break_values_header_odd_margin,           &page_hefo_break_values_header_odd_margin_data },
    { &page_hefo_break_values_header_odd_margin_label,     &page_hefo_break_values_hf_oef_margin_label_data },
    { &page_hefo_break_values_header_odd_margin_units,     &page_hefo_break_values_hf_oef_units_data },
    { &page_hefo_break_values_header_odd_offset,           &page_hefo_break_values_header_odd_offset_data },
    { &page_hefo_break_values_header_odd_offset_label,     &page_hefo_break_values_hf_oef_offset_label_data },
    { &page_hefo_break_values_header_odd_offset_units,     &page_hefo_break_values_hf_oef_units_data },

    { &page_hefo_break_values_header_even_group,           &page_hefo_break_values_header_even_group_data },
    { &page_hefo_break_values_header_even_group2,          NULL /*&page_hefo_break_values_hf_oef_group2_data*/ },
    { &page_hefo_break_values_header_even_caption_group2 },
    { &page_hefo_break_values_header_even_enable,          &page_hefo_break_values_header_even_enable_data },
    { &page_hefo_break_values_header_even_margin,          &page_hefo_break_values_header_even_margin_data },
    { &page_hefo_break_values_header_even_margin_label,    &page_hefo_break_values_hf_oef_margin_label_data },
    { &page_hefo_break_values_header_even_margin_units,    &page_hefo_break_values_hf_oef_units_data },
    { &page_hefo_break_values_header_even_offset,          &page_hefo_break_values_header_even_offset_data },
    { &page_hefo_break_values_header_even_offset_label,    &page_hefo_break_values_hf_oef_offset_label_data },
    { &page_hefo_break_values_header_even_offset_units,    &page_hefo_break_values_hf_oef_units_data },

    { &page_hefo_break_values_header_first_group,          &page_hefo_break_values_header_first_group_data },
    { &page_hefo_break_values_header_first_group2,         NULL /*&page_hefo_break_values_hf_oef_group2_data*/ },
    { &page_hefo_break_values_header_first_caption_group2 },
    { &page_hefo_break_values_header_first_enable,         &page_hefo_break_values_header_first_enable_data },
    { &page_hefo_break_values_header_first_margin,         &page_hefo_break_values_header_first_margin_data },
    { &page_hefo_break_values_header_first_margin_label,   &page_hefo_break_values_hf_oef_margin_label_data },
    { &page_hefo_break_values_header_first_margin_units,   &page_hefo_break_values_hf_oef_units_data },
    { &page_hefo_break_values_header_first_offset,         &page_hefo_break_values_header_first_offset_data },
    { &page_hefo_break_values_header_first_offset_label,   &page_hefo_break_values_hf_oef_offset_label_data },
    { &page_hefo_break_values_header_first_offset_units,   &page_hefo_break_values_hf_oef_units_data },

    { &page_hefo_break_values_footer_odd_group,            &page_hefo_break_values_footer_odd_group_data },
    { &page_hefo_break_values_footer_odd_group2,           NULL /*&page_hefo_break_values_hf_oef_group2_data*/ },
    { &page_hefo_break_values_footer_odd_caption_group2 },
    { &page_hefo_break_values_footer_odd_enable,           &page_hefo_break_values_footer_odd_enable_data },
    { &page_hefo_break_values_footer_odd_margin,           &page_hefo_break_values_footer_odd_margin_data },
    { &page_hefo_break_values_footer_odd_margin_label,     &page_hefo_break_values_hf_oef_margin_label_data },
    { &page_hefo_break_values_footer_odd_margin_units,     &page_hefo_break_values_hf_oef_units_data },
    { &page_hefo_break_values_footer_odd_offset,           &page_hefo_break_values_footer_odd_offset_data },
    { &page_hefo_break_values_footer_odd_offset_label,     &page_hefo_break_values_hf_oef_offset_label_data },
    { &page_hefo_break_values_footer_odd_offset_units,     &page_hefo_break_values_hf_oef_units_data },

    { &page_hefo_break_values_footer_even_group,           &page_hefo_break_values_footer_even_group_data },
    { &page_hefo_break_values_footer_even_group2,          NULL /*&page_hefo_break_values_hf_oef_group2_data*/ },
    { &page_hefo_break_values_footer_even_caption_group2 },
    { &page_hefo_break_values_footer_even_enable,          &page_hefo_break_values_footer_even_enable_data },
    { &page_hefo_break_values_footer_even_margin,          &page_hefo_break_values_footer_even_margin_data },
    { &page_hefo_break_values_footer_even_margin_label,    &page_hefo_break_values_hf_oef_margin_label_data },
    { &page_hefo_break_values_footer_even_margin_units,    &page_hefo_break_values_hf_oef_units_data },
    { &page_hefo_break_values_footer_even_offset,          &page_hefo_break_values_footer_even_offset_data },
    { &page_hefo_break_values_footer_even_offset_label,    &page_hefo_break_values_hf_oef_offset_label_data },
    { &page_hefo_break_values_footer_even_offset_units,    &page_hefo_break_values_hf_oef_units_data },

    { &page_hefo_break_values_footer_first_group,          &page_hefo_break_values_footer_first_group_data },
    { &page_hefo_break_values_footer_first_group2,         NULL /*&page_hefo_break_values_hf_oef_group2_data*/ },
    { &page_hefo_break_values_footer_first_caption_group2 },
    { &page_hefo_break_values_footer_first_enable,         &page_hefo_break_values_footer_first_enable_data },
    { &page_hefo_break_values_footer_first_margin,         &page_hefo_break_values_footer_first_margin_data },
    { &page_hefo_break_values_footer_first_margin_label,   &page_hefo_break_values_hf_oef_margin_label_data },
    { &page_hefo_break_values_footer_first_margin_units,   &page_hefo_break_values_hf_oef_units_data },
    { &page_hefo_break_values_footer_first_offset,         &page_hefo_break_values_footer_first_offset_data },
    { &page_hefo_break_values_footer_first_offset_label,   &page_hefo_break_values_hf_oef_offset_label_data },
    { &page_hefo_break_values_footer_first_offset_units,   &page_hefo_break_values_hf_oef_units_data },

    { &page_hefo_break_values_page_break,                  &page_hefo_break_values_page_break_data },
    { &page_hefo_break_values_page_number,                 &page_hefo_break_values_page_number_data },
    { &page_hefo_break_values_page_number_enable,          &page_hefo_break_values_page_number_enable_data },

    { &page_hefo_break_values_ok, &page_hefo_break_values_ok_data },
    { &stdbutton_cancel, &stdbutton_cancel_data }
};

typedef struct PAGE_HEFO_BREAK_VALUES_CALLBACK
{
    ROW row;
}
PAGE_HEFO_BREAK_VALUES_CALLBACK, * P_PAGE_HEFO_BREAK_VALUES_CALLBACK;

_Check_return_
static STATUS
dialog_page_hefo_break_values_preprocess_command(
    _InoutRef_  P_DIALOG_MSG_PREPROCESS_COMMAND p_dialog_msg_preprocess_command)
{
    const P_PAGE_HEFO_BREAK_VALUES_CALLBACK p_page_hefo_break_values_callback = (P_PAGE_HEFO_BREAK_VALUES_CALLBACK) p_dialog_msg_preprocess_command->client_handle;
    const U32 n_args = n_arglist_args(&p_dialog_msg_preprocess_command->arglist_handle);
    const P_ARGLIST_ARG p_args = p_arglist_args(&p_dialog_msg_preprocess_command->arglist_handle, n_args);
    U32 arg_idx;

    for(arg_idx = 0; arg_idx < n_args; ++arg_idx)
    {
        const P_ARGLIST_ARG p_arg = &p_args[arg_idx];

        switch(arg_idx)
        {
        case ARG_PAGE_HEFO_BREAK_VALUES_ROW:
            p_arg->type    = ARG_TYPE_ROW;
            p_arg->val.row = p_page_hefo_break_values_callback->row;
            break;

        case ARG_PAGE_HEFO_BREAK_VALUES_PAGE_BREAK:
        case ARG_PAGE_HEFO_BREAK_VALUES_PAGE_NUMBER:
            break;

        default: default_unhandled();
#if CHECKING
        case ARG_PAGE_HEFO_BREAK_VALUES_HEADER_ODD_MARGIN:
        case ARG_PAGE_HEFO_BREAK_VALUES_HEADER_ODD_OFFSET:
        case ARG_PAGE_HEFO_BREAK_VALUES_HEADER_EVEN_MARGIN:
        case ARG_PAGE_HEFO_BREAK_VALUES_HEADER_EVEN_OFFSET:
        case ARG_PAGE_HEFO_BREAK_VALUES_HEADER_FIRST_MARGIN:
        case ARG_PAGE_HEFO_BREAK_VALUES_HEADER_FIRST_OFFSET:
        case ARG_PAGE_HEFO_BREAK_VALUES_FOOTER_ODD_MARGIN:
        case ARG_PAGE_HEFO_BREAK_VALUES_FOOTER_ODD_OFFSET:
        case ARG_PAGE_HEFO_BREAK_VALUES_FOOTER_EVEN_MARGIN:
        case ARG_PAGE_HEFO_BREAK_VALUES_FOOTER_EVEN_OFFSET:
        case ARG_PAGE_HEFO_BREAK_VALUES_FOOTER_FIRST_MARGIN:
        case ARG_PAGE_HEFO_BREAK_VALUES_FOOTER_FIRST_OFFSET:
#endif
            if(p_arg->type == ARG_TYPE_F64) /* as opposed to ARG_TYPE_NONE */
                p_arg->val.fp_pixit = (FP_PIXIT) ((PIXIT) (/*FP_USER_UNIT*/ p_arg->val.f64 * page_hefo_break_values_fp_pixits_per_user_unit + 0.5));
            break;

        case ARG_PAGE_HEFO_BREAK_VALUES_PAGE_NUMBER_DEFINE:
            if(p_arg->type == ARG_TYPE_BOOL)
                if(!p_arg->val.fBool)
                {
                    /* if not defining, nobble the associated arg */
                    arg_dispose(&p_dialog_msg_preprocess_command->arglist_handle,
                                (arg_idx - ARG_PAGE_HEFO_BREAK_VALUES_PAGE_NUMBER_DEFINE) + ARG_PAGE_HEFO_BREAK_VALUES_PAGE_NUMBER);
                }
            break;

        case ARG_PAGE_HEFO_BREAK_VALUES_HEADER_ODD_DEFINE:
        case ARG_PAGE_HEFO_BREAK_VALUES_HEADER_EVEN_DEFINE:
        case ARG_PAGE_HEFO_BREAK_VALUES_HEADER_FIRST_DEFINE:
        case ARG_PAGE_HEFO_BREAK_VALUES_FOOTER_ODD_DEFINE:
        case ARG_PAGE_HEFO_BREAK_VALUES_FOOTER_EVEN_DEFINE:
        case ARG_PAGE_HEFO_BREAK_VALUES_FOOTER_FIRST_DEFINE:
            if(p_arg->type == ARG_TYPE_BOOL)
                if(!p_arg->val.fBool)
                {
                    /* if not defining, nobble the associated args */
                    arg_dispose(&p_dialog_msg_preprocess_command->arglist_handle,
                                (arg_idx - ARG_PAGE_HEFO_BREAK_VALUES_HEADER_ODD_DEFINE) + ARG_PAGE_HEFO_BREAK_VALUES_HEADER_ODD_MARGIN);
                    arg_dispose(&p_dialog_msg_preprocess_command->arglist_handle,
                                (arg_idx - ARG_PAGE_HEFO_BREAK_VALUES_HEADER_ODD_DEFINE) + ARG_PAGE_HEFO_BREAK_VALUES_HEADER_ODD_OFFSET);
                }
            break;
        }
    }

    return(STATUS_OK);
}

_Check_return_
static STATUS
dialog_page_hefo_break_values_create_state(
    _InoutRef_  P_DIALOG_MSG_CTL_CREATE_STATE p_dialog_msg_ctl_create_state)
{
    switch(p_dialog_msg_ctl_create_state->dialog_control_id)
    {
    case PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_ENABLE:
    case PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_ENABLE:
    case PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_ENABLE:
    case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_ENABLE:
    case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_ENABLE:
    case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_ENABLE:
    case PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER_ENABLE:
        p_dialog_msg_ctl_create_state->state_set.bits |= DIALOG_STATE_SET_ALWAYS_MSG;
        break;

    default:
        break;
    }

    return(STATUS_OK);
}

_Check_return_
static STATUS
dialog_page_hefo_break_values_ctl_state_change(
    _InRef_     PC_DIALOG_MSG_CTL_STATE_CHANGE p_dialog_msg_ctl_state_change)
{
    const DIALOG_CONTROL_ID dialog_control_id = p_dialog_msg_ctl_state_change->dialog_control_id;
    DIALOG_CONTROL_ID disable_dialog_control_id;

    switch(dialog_control_id)
    {
    case PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_ENABLE:
    case PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_ENABLE:
    case PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_ENABLE:
    case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_ENABLE:
    case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_ENABLE:
    case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_ENABLE:
        disable_dialog_control_id = (DIALOG_CONTROL_ID) ((dialog_control_id - PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_ENABLE) + PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_GROUP2);
        break;

    case PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER_ENABLE:
        disable_dialog_control_id = (DIALOG_CONTROL_ID) ((dialog_control_id - PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER_ENABLE) + PAGE_HEFO_BREAK_VALUES_ID_PAGE_NUMBER);
        break;

    default:
        return(STATUS_OK);
    }

    ui_dlg_ctl_enable(p_dialog_msg_ctl_state_change->h_dialog, disable_dialog_control_id, (p_dialog_msg_ctl_state_change->new_state.checkbox == DIALOG_BUTTONSTATE_ON));

    return(STATUS_OK);
}

PROC_DIALOG_EVENT_PROTO(static, dialog_event_page_hefo_break_values)
{
    UNREFERENCED_PARAMETER_DocuRef_(p_docu);

    switch(dialog_message)
    {
    case DIALOG_MSG_CODE_PREPROCESS_COMMAND:
        return(dialog_page_hefo_break_values_preprocess_command((P_DIALOG_MSG_PREPROCESS_COMMAND) p_data));

    case DIALOG_MSG_CODE_CTL_CREATE_STATE:
        return(dialog_page_hefo_break_values_create_state((P_DIALOG_MSG_CTL_CREATE_STATE) p_data));

    case DIALOG_MSG_CODE_CTL_STATE_CHANGE:
        return(dialog_page_hefo_break_values_ctl_state_change((PC_DIALOG_MSG_CTL_STATE_CHANGE) p_data));

    default:
        return(STATUS_OK);
    }
}

static void
page_hefo_break_values_precreate(
    _DocuRef_   P_DOCU p_docu,
    P_DIALOG_CMD_PROCESS_DBOX p_dialog_cmd_process_dbox)
{
    SCALE_INFO scale_info;
    DISPLAY_UNIT_INFO display_unit_info;
    STATUS numform_resource_id;

    /* reflect current measurement system in dialogue box */
    scale_info_from_docu(p_docu, FALSE, &scale_info);

    /* allow bumping to finest usable resolution */
    page_hefo_break_values_user_unit_multiple = ((F64) scale_info.coarse_div * scale_info.fine_div) / scale_info.numbered_units_multiplier;

    display_unit_info_from_display_unit(&display_unit_info, scale_info.display_unit);

    page_hefo_break_values_fp_pixits_per_user_unit = display_unit_info.fp_pixits_per_unit;

    switch(scale_info.display_unit)
    {
    default: default_unhandled();
#if CHECKING
    case DISPLAY_UNIT_CM:
#endif
        page_hefo_break_values_user_unit_resource_id = MSG_DIALOG_UNITS_CM;
        numform_resource_id = MSG_DIALOG_STYLE_NUMFORM_CM;
        break;

    case DISPLAY_UNIT_MM:
        page_hefo_break_values_user_unit_resource_id = MSG_DIALOG_UNITS_MM;
        numform_resource_id = MSG_DIALOG_STYLE_NUMFORM_MM;
        break;

    case DISPLAY_UNIT_INCHES:
        page_hefo_break_values_user_unit_resource_id = MSG_DIALOG_UNITS_INCHES;
        numform_resource_id = MSG_DIALOG_STYLE_NUMFORM_INCHES;
        break;

    case DISPLAY_UNIT_POINTS:
        page_hefo_break_values_user_unit_resource_id = MSG_DIALOG_UNITS_POINTS;
        numform_resource_id = MSG_DIALOG_STYLE_NUMFORM_POINTS;
        break;
    }

    resource_lookup_ustr_buffer(ustr_bptr(page_hefo_break_values_user_unit_numform_ustr_buf), elemof32(page_hefo_break_values_user_unit_numform_ustr_buf), numform_resource_id);

    {
    UI_CONTROL_F64 * p_ui_control_f64 = &page_hefo_break_values_units_control;

    p_ui_control_f64->ustr_numform  = ustr_bptr(page_hefo_break_values_user_unit_numform_ustr_buf);
    p_ui_control_f64->inc_dec_round = page_hefo_break_values_user_unit_multiple;
    p_ui_control_f64->bump_val      = 1.0 / p_ui_control_f64->inc_dec_round;
    p_ui_control_f64->min_val       = 0.0;

    switch(scale_info.display_unit)
    {
    default: default_unhandled();
#if CHECKING
    case DISPLAY_UNIT_CM:
#endif
        p_ui_control_f64->max_val = 100.0;
        break;

    case DISPLAY_UNIT_MM:
        p_ui_control_f64->max_val = 1000.0;
        break;

    case DISPLAY_UNIT_INCHES:
        p_ui_control_f64->max_val = 10.0;
        break;

    case DISPLAY_UNIT_POINTS:
        p_ui_control_f64->max_val = 10.0 * PIXITS_PER_INCH;
        break;
    }
    } /*block*/

    page_hefo_break_values_hf_oef_units_data.caption.type = UI_TEXT_TYPE_RESID;
    page_hefo_break_values_hf_oef_units_data.caption.text.resource_id = page_hefo_break_values_user_unit_resource_id;

    { /* quick pre-create pass */
    U32 i;

    assert(NULL != p_dialog_cmd_process_dbox->p_ctl_create);

    for(i = 0; i < p_dialog_cmd_process_dbox->n_ctls; ++i)
    {
        const P_DIALOG_CTL_CREATE p_dialog_ctl_create = &p_dialog_cmd_process_dbox->p_ctl_create[i];

        switch(p_dialog_ctl_create->p_dialog_control.p_dialog_control->dialog_control_id)
        {
        case PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_MARGIN:
        case PAGE_HEFO_BREAK_VALUES_ID_HEADER_ODD_OFFSET:
        case PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_MARGIN:
        case PAGE_HEFO_BREAK_VALUES_ID_HEADER_EVEN_OFFSET:
        case PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_MARGIN:
        case PAGE_HEFO_BREAK_VALUES_ID_HEADER_FIRST_OFFSET:
        case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_MARGIN:
        case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_ODD_OFFSET:
        case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_MARGIN:
        case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_EVEN_OFFSET:
        case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_MARGIN:
        case PAGE_HEFO_BREAK_VALUES_ID_FOOTER_FIRST_OFFSET:
            {
            const PC_DIALOG_CONTROL_DATA_BUMP_F64 p_dialog_control_data_bump_f64 = (PC_DIALOG_CONTROL_DATA_BUMP_F64) p_dialog_ctl_create->p_dialog_control_data;
            P_F64 p_f64 = de_const_cast(P_F64, &p_dialog_control_data_bump_f64->state);
            *p_f64 = /*FP_USER_UNIT*/ (/*FP_PIXIT*/ *p_f64 / page_hefo_break_values_fp_pixits_per_user_unit);
            break;
            }

        default:
            break;
        }
    }
    } /*block*/
}

static void
values_setup_from(
    P_PAGE_HEFO_SELECTOR p_values_selector,
    P_PAGE_HEFO_BREAK p_page_hefo_break,
    _InVal_     BOOL on)
{
    if(!page_hefo_selector_bit_test(p_values_selector, PAGE_HEFO_HEADER_ODD))
        if(page_hefo_selector_bit_test(&p_page_hefo_break->selector, PAGE_HEFO_HEADER_ODD))
        {
            page_hefo_selector_bit_set(p_values_selector, PAGE_HEFO_HEADER_ODD);
            page_hefo_break_values_header_odd_enable_data.checkbox.init_state = (U8) (on);
            page_hefo_break_values_header_odd_margin_data.state   = (F64) p_page_hefo_break->header_odd.headfoot_sizes.margin;
            page_hefo_break_values_header_odd_offset_data.state   = (F64) p_page_hefo_break->header_odd.headfoot_sizes.offset;
        }

    if(!page_hefo_selector_bit_test(p_values_selector, PAGE_HEFO_HEADER_EVEN))
        if(page_hefo_selector_bit_test(&p_page_hefo_break->selector, PAGE_HEFO_HEADER_EVEN))
        {
            page_hefo_selector_bit_set(p_values_selector, PAGE_HEFO_HEADER_EVEN);
            page_hefo_break_values_header_even_enable_data.checkbox.init_state = (U8) (on);
            page_hefo_break_values_header_even_margin_data.state  = (F64) p_page_hefo_break->header_even.headfoot_sizes.margin;
            page_hefo_break_values_header_even_offset_data.state  = (F64) p_page_hefo_break->header_even.headfoot_sizes.offset;
        }

    if(!page_hefo_selector_bit_test(p_values_selector, PAGE_HEFO_HEADER_FIRST))
        if(page_hefo_selector_bit_test(&p_page_hefo_break->selector, PAGE_HEFO_HEADER_FIRST))
        {
            page_hefo_selector_bit_set(p_values_selector, PAGE_HEFO_HEADER_FIRST);
            page_hefo_break_values_header_first_enable_data.checkbox.init_state = (U8) (on);
            page_hefo_break_values_header_first_margin_data.state = (F64) p_page_hefo_break->header_first.headfoot_sizes.margin;
            page_hefo_break_values_header_first_offset_data.state = (F64) p_page_hefo_break->header_first.headfoot_sizes.offset;
        }

    if(!page_hefo_selector_bit_test(p_values_selector, PAGE_HEFO_FOOTER_ODD))
        if(page_hefo_selector_bit_test(&p_page_hefo_break->selector, PAGE_HEFO_FOOTER_ODD))
        {
            page_hefo_selector_bit_set(p_values_selector, PAGE_HEFO_FOOTER_ODD);
            page_hefo_break_values_footer_odd_enable_data.checkbox.init_state = (U8) (on);
            page_hefo_break_values_footer_odd_margin_data.state   = (F64) p_page_hefo_break->footer_odd.headfoot_sizes.margin;
            page_hefo_break_values_footer_odd_offset_data.state   = (F64) p_page_hefo_break->footer_odd.headfoot_sizes.offset;
        }

    if(!page_hefo_selector_bit_test(p_values_selector, PAGE_HEFO_FOOTER_EVEN))
        if(page_hefo_selector_bit_test(&p_page_hefo_break->selector, PAGE_HEFO_FOOTER_EVEN))
        {
            page_hefo_selector_bit_set(p_values_selector, PAGE_HEFO_FOOTER_EVEN);
            page_hefo_break_values_footer_even_enable_data.checkbox.init_state= (U8) (on);
            page_hefo_break_values_footer_even_margin_data.state  = (F64) p_page_hefo_break->footer_even.headfoot_sizes.margin;
            page_hefo_break_values_footer_even_offset_data.state  = (F64) p_page_hefo_break->footer_even.headfoot_sizes.offset;
        }

    if(!page_hefo_selector_bit_test(p_values_selector, PAGE_HEFO_FOOTER_FIRST))
        if(page_hefo_selector_bit_test(&p_page_hefo_break->selector, PAGE_HEFO_FOOTER_FIRST))
        {
            page_hefo_selector_bit_set(p_values_selector, PAGE_HEFO_FOOTER_FIRST);
            page_hefo_break_values_footer_first_enable_data.checkbox.init_state = (U8) (on);
            page_hefo_break_values_footer_first_margin_data.state = (F64) p_page_hefo_break->footer_first.headfoot_sizes.margin;
            page_hefo_break_values_footer_first_offset_data.state = (F64) p_page_hefo_break->footer_first.headfoot_sizes.offset;
        }
}

static void
ui_page_hefo_break_textual_representation(
    _DocuRef_   P_DOCU p_docu,
    _InVal_     ROW row,
    _Out_writes_z_(elemof_buffer) P_USTR ustr_buf,
    _InVal_     U32 elemof_buffer)
{
    PAGE page_y = cur_page_y(p_docu);
    BOOL is_page = 0;
    STATUS msg;
    S32 arg;

    if(row == row_from_page_y(p_docu, page_y))
        /* direct hit at top of page */
        is_page = 1;

    msg = is_page ? MSG_DIALOG_HEFO_REPR_PAGE : MSG_DIALOG_HEFO_REPR_ROW;
    arg = is_page ? ((S32) page_y + 1)        : ((S32) row  + 1);

    consume_int(ustr_xsnprintf(ustr_buf, elemof_buffer, resource_lookup_ustr(msg), arg));
}

T5_CMD_PROTO(extern, t5_cmd_page_hefo_break_values_interactive)
{
    const PC_ARGLIST_ARG p_args = pc_arglist_args(&p_t5_cmd->arglist_handle, ARG_PAGE_HEFO_BREAK_VALUES_ROW+1);
    ROW row = p_args[ARG_PAGE_HEFO_BREAK_VALUES_ROW].val.row;
    P_PAGE_HEFO_BREAK p_page_hefo_break;
    PAGE_HEFO_BREAK_VALUES_CALLBACK page_hefo_break_values_callback;
    UCHARZ name_ustr_buf[256];
    PAGE_HEFO_SELECTOR selector;
    STATUS status;

    UNREFERENCED_PARAMETER_InVal_(t5_message);

    page_hefo_break_values_callback.row = row;

    /* encode initial state of control(s) */

    /* supply some defaults */
    page_hefo_break_values_page_break_data.init_state = 0;
    page_hefo_break_values_page_number_enable_data.checkbox.init_state = 0;
    page_hefo_break_values_page_number_data.state = 0;

    page_hefo_break_values_header_odd_enable_data.checkbox.init_state = 0;
    page_hefo_break_values_header_odd_margin_data.state   = (FP_PIXIT) HEADER_DEFAULT_MARGIN;
    page_hefo_break_values_header_odd_offset_data.state   = (FP_PIXIT) HEADER_DEFAULT_OFFSET;

    page_hefo_break_values_header_even_enable_data.checkbox.init_state = 0;
    page_hefo_break_values_header_even_margin_data.state  = (FP_PIXIT) HEADER_DEFAULT_MARGIN;
    page_hefo_break_values_header_even_offset_data.state  = (FP_PIXIT) HEADER_DEFAULT_OFFSET;

    page_hefo_break_values_header_first_enable_data.checkbox.init_state = 0;
    page_hefo_break_values_header_first_margin_data.state = (FP_PIXIT) HEADER_DEFAULT_MARGIN;
    page_hefo_break_values_header_first_offset_data.state = (FP_PIXIT) HEADER_DEFAULT_OFFSET;

    page_hefo_break_values_footer_odd_enable_data.checkbox.init_state = 0;
    page_hefo_break_values_footer_odd_margin_data.state   = (FP_PIXIT) FOOTER_DEFAULT_MARGIN;
    page_hefo_break_values_footer_odd_offset_data.state   = (FP_PIXIT) FOOTER_DEFAULT_OFFSET;

    page_hefo_break_values_footer_even_enable_data.checkbox.init_state = 0;
    page_hefo_break_values_footer_even_margin_data.state  = (FP_PIXIT) FOOTER_DEFAULT_MARGIN;
    page_hefo_break_values_footer_even_offset_data.state  = (FP_PIXIT) FOOTER_DEFAULT_OFFSET;

    page_hefo_break_values_footer_first_enable_data.checkbox.init_state = 0;
    page_hefo_break_values_footer_first_margin_data.state = (FP_PIXIT) FOOTER_DEFAULT_MARGIN;
    page_hefo_break_values_footer_first_offset_data.state = (FP_PIXIT) FOOTER_DEFAULT_OFFSET;

    bitmap_clear(selector.bitmap, N_BITS_ARG(PAGE_HEFO_COUNT));

    p_page_hefo_break = p_page_hefo_break_from_row_exact(p_docu, row);

    if(NULL != p_page_hefo_break)
    {
        if(page_hefo_selector_bit_test(&p_page_hefo_break->selector, PAGE_HEFO_PAGE_BREAK))
            page_hefo_break_values_page_break_data.init_state          = 1;

        if(page_hefo_selector_bit_test(&p_page_hefo_break->selector, PAGE_HEFO_PAGE_NUM))
        {
            page_hefo_break_values_page_number_enable_data.checkbox.init_state  = 1;
            page_hefo_break_values_page_number_data.state = p_page_hefo_break->page_y + 1;
        }

        values_setup_from(&selector, p_page_hefo_break, DIALOG_BUTTONSTATE_ON);
    }
    else
    {
        page_hefo_break_values_page_break_data.init_state = 1; /* always suggest he creates a page break here */
    }

    /* supply defaults from nearest instance of each thing? */
    p_page_hefo_break = p_page_hefo_break_from_row_exact(p_docu, 0);

    if(NULL != p_page_hefo_break)
        values_setup_from(&selector, p_page_hefo_break, DIALOG_BUTTONSTATE_OFF);

    ui_page_hefo_break_textual_representation(p_docu, row, ustr_bptr(name_ustr_buf), elemof32(name_ustr_buf));

    {
    DIALOG_CMD_PROCESS_DBOX dialog_cmd_process_dbox;
    dialog_cmd_process_dbox_setup(&dialog_cmd_process_dbox, page_hefo_break_values_ctl_create, elemof32(page_hefo_break_values_ctl_create), MSG_DIALOG_PAGE_HEFO_BREAK_INTRO_HELP_TOPIC);
    dialog_cmd_process_dbox.caption.type = UI_TEXT_TYPE_USTR_PERM;
    dialog_cmd_process_dbox.caption.text.ustr = ustr_bptr(name_ustr_buf);
    dialog_cmd_process_dbox.p_proc_client = dialog_event_page_hefo_break_values;
    dialog_cmd_process_dbox.client_handle = (CLIENT_HANDLE) &page_hefo_break_values_callback;
    page_hefo_break_values_precreate(p_docu, &dialog_cmd_process_dbox);
    status = object_call_DIALOG_with_docu(p_docu, DIALOG_CMD_CODE_PROCESS_DBOX, &dialog_cmd_process_dbox);
    } /*block*/

    return(status);
}

/* end of ui_hefo.c */
